- name: configure shadowsocks
  gather_facts: True
  hosts: localhost

- hosts: shadowsocks
  handlers:
    - name: restart shadowsocks
    service: name=shadowsocks state=restarted enabled=yes

  tasks:
    - apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
      with_items:
        - shadowsocks

    - copy:
      src: shadowsocks.json
      dest: /etc/shadowsocks/config.json
      notify: restart shadowsocks
